Projet.create!([
  {nom: "AEMMS", 
    url: "https://aemms-v3.herokuapp.com/", 
    contenu: "Système de management de la qualité pour les entreprises de soudage par aluminothermie. 
    Conception, développement et mise en œuvre d'une application Web et mobile sur tablettes Windows (C#/Winform/Ruby on Rails/JSON API).
    Le système a pour objet de s’assurer que les soudures aluminothermiques réalisées sur les voies, dont la SNCF a la responsabilité de la maintenance, satisfont en tous points aux exigences spécifiées par à la Norme européenne EN 14730-2. cf “Cahier des prescriptions communes applicables aux marchés de travaux de voie.
    Application déployée chez plusieurs prestataires de la SNCF (ETF, LSF, Colas Rail, SOTRAMEST, ...)", 
    poids: 100, 
    commit: 217, 
    deploy: 129, 
    coffee: 90, 
    tag_list: "Rails 7, DaisyUI, TailwindCSS" },
  {nom: "RNMA", 
    url: "https//www.rnma.fr/", 
    contenu: "Plateforme de gestion du portefeuille d'adhérents du Réseau National des Maisons des Associations. 
    Comprend : la gestion des adhésions, des cotisations, des contacts, des actions, et des ressources documentaires. 
    Un portail réservé aux membres du RNMA permet la consultations d'informations ciblées et la discussion entre membres via un 'mini réseau social' interne. ",
    poids: 90, 
    commit: 1196, 
    deploy: 468, 
    coffee: 265, 
    tag_list: "Stimulus, JS, Bulma, Rails 6"},
  {nom: "INNOSERV", 
    url: "https://innoserv-project.herokuapp.com/", 
    contenu: "INNOSERV est un projet développant un programme de recherche à l'échelle de l'UE pour évaluer l'innovation dans le domaine des services sociaux (en particulier pour les services de santé, d'éducation et d'aide sociale). Cela aidera à définir les futures activités de recherche.", 
    poids: 80, 
    commit: 113, 
    deploy: 38, 
    coffee: 13, 
    tag_list: "JS, Bootstrap, Rails 6"},
  {nom: "PLANNING IAE-PARIS", 
    url: "https://planning-iae.herokuapp.com/", 
    contenu: "Application de gestion de Planning de l'IAE Paris - Sorbonne Business School - Université Paris 1 Panthéon-Sorbonne. Application web de planification de cours. Collaborative, flexible et simple d'utilisation.", 
    poids: 70, 
    commit: 771, 
    deploy: 482, 
    coffee: 138, 
    tag_list: "Stimulus, Bootstrap, Rails 6"},
  {nom: "Disturbances", 
    url: "https://disturbances.herokuapp.com/", 
    contenu: "Outil de collecte et d'analyse des perturbations du traffic TER Grand Est, à l'usage de la FNAUT-Est.", 
    poids: 60, 
    commit: 179, 
    deploy: 85, 
    coffee: 27, 
    tag_list: "Rails 7, DaisyUI, TailwindCSS" },
  {nom: "LTSF pro", 
    url: "https://www.ltsf.pro", 
    contenu: "Plateforme de cotation B2B à l'usage des grossistes du pionnier du T-Shirt français. Conception et développement d'une plateforme B2B pour le pionnier du T-shirt de fabrication française. Cet outil permet de gérer un catalogue des produits, l'état des stocks par taille, et, pour un utilisateur habilité, d'effectuer des cotations aux tarifs de gros. ", 
    poids: 50, 
    commit: 295, 
    deploy: 250, 
    coffee: 43, 
    tag_list: "Stimulus, Bulma, Rails 6"},
  {nom: "Prestofacto", 
    url: "https://prestofacto.philnoug.com/", 
    contenu: "Application libre de facturation de services journaliers. PrestoFacto aide les petites organisations dans la gestion et la facturation de leurs prestations journalières (Repas, garderie, péri-scolaire).", 
    poids: 40, 
    commit: 395, 
    deploy: 226, 
    coffee: 74, 
    tag_list: "Bulma, Rails 6"},
  {nom: "Affichage-Planning", 
    url: "https://tableau-affichage-horaires-iae.herokuapp.com/", 
    contenu: "Tableau d'affichage dynamique des Horaires de Cours, optimisé pour défilement sur grand écran.", 
    poids: 30, 
    commit: 20, 
    deploy: 20, 
    coffee: 9, 
    tag_list: "React, Rails 6, React on Rails"},
  {nom: "Portfolio", 
    url: "https://portfolio-philnoug.herokuapp.com/", 
    contenu: "C'est le portfolio de l'essentiel de nos projets de l'année, mais il en manque encore quelques-un !", 
    poids: 20, 
    commit: 43, 
    deploy: 17, 
    coffee: 13,
    tag_list: "Rails 7, DaisyUI, TailwindCSS" }
])
