Projet.create!([
  {nom: "AEMMS", 
    url: "https://aemms-v3.herokuapp.com/", 
    contenu: "Système de management de la qualité pour les entreprises de soudage par aluminothermie.", 
    poids: 100, 
    tag_list: "Rails 7, DaisyUI, TailwindCSS" },
  {nom: "RNMA", 
    url: "https//www.rnma.fr/", 
    contenu: "Les Maisons des associations au service de la vie associative locale.",
    poids: 90, 
    tag_list: "Stimulus, Bulma, Rails 6"},
  {nom: "INNOSERV", 
    url: "https://innoserv-project.herokuapp.com/", 
    contenu: "INNOSERV est un projet développant un programme de recherche à l'échelle de l'UE pour évaluer l'innovation dans le domaine des services sociaux (en particulier pour les services de santé, d'éducation et d'aide sociale). Cela aidera à définir les futures activités de recherche.", 
    poids: 80, 
    tag_list: "Stimulus, Bootstrap, Rails 6"},
  {nom: "IAE PLANNING", 
    url: "https://planning-iae.herokuapp.com/", 
    contenu: "Application web de planification de cours. Collaborative, flexible et simple d'utilisation.", 
    poids: 70, 
    tag_list: "Stimulus, Bootstrap, Rails 6"},
  {nom: "Disturbances", 
    url: "https://disturbances.herokuapp.com/", 
    contenu: "Outil de collecte et d'analyse des perturbations SNCF-TER Grand Est.", 
    poids: 60, 
    tag_list: "Rails 7, DaisyUI, TailwindCSS" },
  {nom: "LTSF pro", 
    url: "https://www.ltsf.pro", 
    contenu: "Plateforme de cotation B2B à l'usage des grossistes du pionnier du T-Shirt français.", 
    poids: 50, 
    tag_list: "Stimulus, Bulma, Rails 6"},
  {nom: "AEMMS-MOBILE", 
    url: "https://aemms-v3.herokuapp.com/about", 
    contenu: "Nouvelle application mobile d'AEMMS, à l'usage des opérateurs de terrain.",
     poids: 40, 
     tag_list: "Android, Xamarin"},
  {nom: "Prestofacto", 
    url: "https://prestofacto.philnoug.com/", 
    contenu: "Application libre de facturation de services journaliers.", 
    poids: 30, 
    tag_list: "Stimulus, Bulma, Rails 6"},
  {nom: "Affichage-Planning", 
      url: "https://tableau-affichage-horaires-iae.herokuapp.com/", 
      contenu: "Tableau d'Affichage des Horaires de Cours.", 
      poids: 20, 
      tag_list: "React, Rails 6, React on Rails"},  
  {nom: "Portfolio", 
    url: "http://127.0.0.1:3000/", 
    contenu: "C'est le portfolio de nos projets de l'année, et il en manque !", 
    poids: 10, 
    tag_list: "Rails 7, DaisyUI, TailwindCSS" },
])
